name: CI Pipeline - Build e Teste (TS/Docker)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Compilar (Build)
        run: npm run build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build da imagem Docker
        run: docker build . --file Dockerfile --tag meu-app-ts:${{ github.run_id }}
